# Generated by Django 2.2.2 on 2019-07-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_user', models.CharField(max_length=128)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('collection_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('metadata', models.TextField()),
                ('filepath', models.TextField(null=True)),
                ('source_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SubmittedData')),
            ],
        ),
    ]
