# Generated by Django 2.2.2 on 2019-07-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190729_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='submitteddata',
            options={'verbose_name': 'Submitted Datum', 'verbose_name_plural': 'Submitted Data'},
        ),
    ]
